<?php global $c, $user_config, $d, $f, $userdata; ?>
<?php 
	if(!isset($_GET['stream_id'])) {
		return false;
	}
	$stream_id = $_GET['stream_id'];

	$stream = new Stream($stream_id);

	$stream_group = new Group($stream->getProperty('group'));

	$streams = new Streams;

	$categories = [
		'trigger' => [
			'sub_categories' => ['main'],
			'icon'           => 'far.arrow-down'
		], 
		'condition' => [
			'sub_categories' => ['main', 'and'],  
			'icon'           => 'far.arrow-down'
		],
		'do' => [
			'sub_categories' => ['main', 'and'],  
			'hr'             => true
		],
		'else' => [
			'sub_categories' => ['main', 'and'],  
		],
	];

	$cards_selected = [];
	foreach ($categories as $category => $category_info) {
		// List of selected cards
		$cards_selected[$category] = $stream->getProperty($category);
	}
?>
<?php foreach($categories as $category => $category_info) : ?>
	<div class="stream-category transition-fade-order tile" data-category="<?php echo($category); ?>">
		<?php foreach ($category_info['sub_categories'] as $sub_category) : ?>
			<?php 
				$category_name = "{$category}_{$sub_category}";
				if($sub_category == 'main') {
					$category_name  = $category;
				}

				switch($category) {
					case 'trigger':
					case 'condition':
						$cards_category = $category;
						break;

					case 'do':
					case 'else':
						$cards_category = 'do';
						break;
				}	
			?>
			<!-- Sub Category -->
			<div class="stream-sub-category" data-sub-category="<?php echo($sub_category); ?>" data-set="false" data-show="false">
				<div class="tile-row flex-column flex-xl-row">
					<!-- Pick card -->
					<div class="col-12 col-xl-4 stream-card-select-wrapper">
						<div class="tile-title stream-category-title"><?php\HomioPi\Locale\translate("streams.action.{$category_name}.title", true); ?></div>
						<input type="text" class="stream-card-search" data-type="search" name="streams_<?php echo($sub_category); ?>" placeholder="<?php\HomioPi\Locale\translate('action.select', true); ?>">
					</div>
					<script>
						$(document).on('homiopi.page_ready', function() {
							let cards_input = $('.stream-category[data-category="<?php echo($category); ?>"] .stream-sub-category[data-sub-category="<?php echo($sub_category); ?>"] .input.stream-card-search');
							<?php 
								$cards = $streams->list_cards($cards_category);
								foreach ($cards as $card_name) {
									$card                 = $streams->load_card($cards_category, $card_name);
									$card_name_translated = \HomioPi\Locale\translate("streams.cards.{$cards_category}.{$card_name}.title");
									$icon_html            = create_icon($card['icon'], 'sm', null, ['color' => $card['group_color']]);
									echo("cards_input.appendResult('{$card_name}', '{$card_name_translated}', '{$card_name_translated}', null, null, '{$icon_html}');");
								}
							?>
						})
					</script>

					<!-- List of cards -->
					<div class="stream-cards col">
						<div class="stream-card tile bg-primary show col-12" id="stream-card-empty" data-stream-card="no_stream_card_selected">
							<div class="tile-row">
								<span class="stream-card-title tile-title text-overflow-ellipsis">
									<?php\HomioPi\Locale\translate('streams.cards.none_selected.title', true); ?>
								</span>
							</div>
							<div class="tile-row">
								<div class="stream-card-content">
									<span class="text-muted"><?php\HomioPi\Locale\translate('streams.cards.none_selected.content', true); ?><span>
								</div>
							</div>
						</div>
						<?php foreach($cards as $card_name) : ?>
							<?php 
								$card = $streams->load_card($cards_category, $card_name); 
								$card_parameters_html = [];
							?>
							<div class="stream-card tile bg-primary" data-stream-card="<?php echo($card_name); ?>">
								<div class="tile-row">
									<span class="stream-card-title tile-title text-overflow-ellipsis"><?php\HomioPi\Locale\translate("streams.card_groups.group.{$card['card_group']}.title", true); ?></span>
									<span class="tile-side-title"><?php echo(create_icon($card['icon'], 'sm', null, ['color' => $card['group_color']])); ?></span>
								</div>
								<div class="tile-row">
									<div class="stream-card-content">
										<?php 
											// List of parameters generated by the Streams class
											foreach ($card['parameters'] as $param_id => $param_values) {
												$param_item_first = null;
												$param_value_first = null;
												$attrs = '';
												
												if(is_array($param_values)) {
													// Search select

													// Create JS code which will list the possible values in a search input
													$param_values_append_script = '';
													$select_type = 'single';

													foreach ($param_values as $param_value => $param_items) {
														if(strpos($param_value, '_') === 0) {
															// Options, not actual parameters
															switch ($param_value) {
																case '_type':
																	$select_type = $param_values['_type'];
																	break;
																case '_sep_between':
																	// Send between-seperator to front-end (most likely a comma)
																	$attrs .= 'data-seperator-between="'.$param_values['_sep_between'].'" ';
																	break;
																case '_sep_end':
																	// Send end-seperator to front-end
																	$attrs .= 'data-seperator-end="'.$param_values['_sep_end'].'" ';
																	break;
															}

															continue;
														}

														$param_value_first = $param_value_first ?? $param_value;

														if(is_array($param_items)) {
															// Rich result
															$param_item_first = $param_item_first ?? $param_items['title'];
															$param_items = array_replace(['title' => 'null', 'description' => 'null', 'thumbnail' => 'null', 'icon' => 'null'], $param_items);
															$param_values_append_script .= "\$input.appendResult('{$param_value}', '{$param_items['title']}', '{$param_items['title']}', '{$param_items['thumbnail']}', '{$param_items['description']}', '{$param_items['icon']}');";
														} else {
															// Plain result
															$param_item_first = $param_item_first ?? $param_items;
															$param_values_append_script .= "\$input.appendResult('{$param_value}', '{$param_items}', '{$param_items}');";
														}
													}

													// Remove extra spaces from attributes list
													$attrs = trim($attrs);

													$card_parameters_html[$param_id] = "
														<span data-type=\"search\" data-select-type=\"{$select_type}\" {$attrs} class=\"input\" placeholder=\"".l('action.select')."\" data-param=\"{$param_id}\"></span>
														<script>
															$(document).on('homiopi.page_ready', function() {
																\$input = $('.stream-category[data-category=\"{$category}\"] > .stream-sub-category[data-sub-category=\"{$sub_category}\"] .stream-cards .stream-card[data-stream-card=\"{$card_name}\"] .input[data-param=\"{$param_id}\"]');
																{$param_values_append_script}
																\$input.setSearchValue('{$param_value_first}', '{$param_item_first}');
															})
														</script>
													";

												} else if(is_string($param_values)) {
													// String or number

													list($type, $attrs) = array_pad(explode(':', $param_values), 2, '');
													$attrs = array_pad(explode(',', $attrs), 3, 'null');

													switch($type) {
														case 'float':
															$card_parameters_html[$param_id] = "<input type=\"number\" data-type=\"float\" data-min=\"{$attrs[0]}\" data-max=\"{$attrs[1]}\" placeholder=\"".l('input_type.float')."\" data-param=\"{$param_id}\">";
															break;

														case 'integer':
															$card_parameters_html[$param_id] = "<input type=\"number\" data-type=\"integer\" data-min=\"{$attrs[0]}\" data-max=\"{$attrs[1]}\" placeholder=\"".l('input_type.integer')."\" data-param=\"{$param_id}\">";
															break;

														case 'string':
															$card_parameters_html[$param_id] = "<span class=\"input\" data-type=\"text\" placeholder=\"".l('input_type.string')."\" data-param=\"{$param_id}\"></span>";
															break;
													}
												}
											}

											l("streams.cards.{$cards_category}.{$card_name}.content", true, $card_parameters_html,\HomioPi\Locale\translate('generic.error'));
										?>
									</div>
								</div>
							</div>
						<?php endforeach; ?>
					</div>
				</div>
			</div>
			<?php endforeach; ?>
		<?php if(in_array('and', $category_info['sub_categories'])) : ?>
			<div class="tile-row category-actions-wrapper">
				<div class="btn bg-tertiary btn-primary stream-add-card-button btn-md-square mx-auto no-active" onclick="addStreamSubCategory($(this).parents('.stream-category').attr('data-category'));">
					<?php echo(create_icon('far.plus', 'md', [], ['color' => $stream_group->getProperty('color')])); ?>
				</div>
			</div>
		<?php endif; ?>
	</div>
	<?php if(isset($category_info['icon'])) : ?>
		<div class="stream-between-category transition-fade-order" data-below-category="<?php echo($category); ?>">
			<?php echo(create_icon($category_info['icon'], 'md', [], ['color' => $stream_group->getProperty('color')])); ?>
		</div>
	<?php elseif(isset($category_info['hr'])) : ?>
		<div class="stream-between-category transition-fade-order" data-below-category="<?php echo($category); ?>">
			<hr style="background: <?php echo($stream_group->getProperty('color')); ?>;">
		</div>
	<?php endif; ?>
<?php endforeach; ?>
<script>
	$(document).on('homiopi.page_ready', function() {
		printStreamCategories('<?php echo($stream_id); ?>');
	})
</script>